import React, { Component } from 'react';
import XtTable from '../../components/XtTable';
import { get, getById, del, update, add, getColumns } from '../../api'

const COLUMNS_CONFIG = [
  {
    id: 123,
    table_id: 29,
    table_name: "c_dbconfig",
    name: "id",
    fieldname: "id",
    title: "id",
    data_type: 0,
    col_show: 1,
    col_width: null,
    col_lock: "false",
    col_unit: null,
    col_sort: 0,
    col_sortable: null,
    col_align: "center",
    form_show: 0,
    form_type: 1,
    form_disabled: 0,
    form_sort: 0,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "",
    create_time: "2018-03-14T08:09:10.000Z"
  },
  {
    id: 126,
    table_id: 29,
    table_name: "c_dbconfig",
    name: "host",
    fieldname: "host",
    title: "主机名",
    data_type: 0,
    col_show: 1,
    col_width: null,
    col_lock: "false",
    col_unit: null,
    col_sort: 1,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 1,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "主机名",
    create_time: "2018-03-14T08:09:10.000Z"
  },
  {
    id: 125,
    table_id: 29,
    table_name: "c_dbconfig",
    name: "port",
    fieldname: "port",
    title: "端口",
    data_type: 0,
    col_show: 1,
    col_width: null,
    col_lock: "false",
    col_unit: null,
    col_sort: 2,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 2,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "端口",
    create_time: "2018-03-14T08:09:10.000Z"
  },
  {
    id: 128,
    table_id: 29,
    table_name: "c_dbconfig",
    name: "user",
    fieldname: "user",
    title: "用户名",
    data_type: 0,
    col_show: 1,
    col_width: null,
    col_lock: "false",
    col_unit: null,
    col_sort: 3,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 3,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "用户名",
    create_time: "2018-03-14T08:09:10.000Z"
  },
  {
    id: 124,
    table_id: 29,
    table_name: "c_dbconfig",
    name: "password",
    fieldname: "password",
    title: "密码",
    data_type: 0,
    col_show: 1,
    col_width: null,
    col_lock: "false",
    col_unit: null,
    col_sort: 4,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 4,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "密码",
    create_time: "2018-03-14T08:09:10.000Z"
  },
  {
    id: 127,
    table_id: 29,
    table_name: "c_dbconfig",
    name: "database",
    fieldname: "database",
    title: "数据库",
    data_type: 0,
    col_show: 1,
    col_width: null,
    col_lock: "false",
    col_unit: null,
    col_sort: 5,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 5,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "数据库",
    create_time: "2018-03-14T08:09:10.000Z"
  },
  {
    id: 129,
    table_id: 29,
    table_name: "c_dbconfig",
    name: "disabled",
    fieldname: "disabled",
    title: "禁用",
    data_type: 0,
    col_show: 1,
    col_width: null,
    col_lock: "false",
    col_unit: null,
    col_sort: 6,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 6,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "禁用",
    create_time: "2018-03-14T08:09:10.000Z"
  },
  {
    id: 130,
    table_id: 29,
    table_name: "c_dbconfig",
    name: "remark",
    fieldname: "remark",
    title: "备注",
    data_type: 0,
    col_show: 1,
    col_width: null,
    col_lock: "false",
    col_unit: null,
    col_sort: 7,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 7,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "备注",
    create_time: "2018-03-14T08:09:10.000Z"
  }
]

const FILTER = [
  { text: "数据库", value: "database" },
  { text: "主机名", value: "host" },
  { text: "禁用", value: "disabled" },
]

export default class DbConfigTable extends Component {
  static displayName = 'DbConfigTable';
  render() {
    const TABLE_NAME = 'c_dbconfig'
    const api = { get, getById, del, update, add, getColumns }
    // 这里的key不能少，否则react会缓存，不重新渲染
    return (
      <div className="table-page" key={TABLE_NAME}>
        <XtTable {...api} name={TABLE_NAME} columns={COLUMNS_CONFIG} filter={FILTER} />
      </div>
    );
  }
}
