/**
 * 定义应用路由
 */
import React from 'react'
import {
  Router,
  // browserHistory,
  hashHistory,
} from 'react-router'

// 路由配置规则参考： https://github.com/ReactTraining/react-router/blob/v3/docs/guides/RouteConfiguration.md#configuration-with-plain-routes
// 一下部分是由 ICE 相关工具自动生成的路由，请勿随意改变，否则可能会出现一些异常情况
// <!-- auto generated routes start -->
const autoGeneratedRoutes = [];

// <!-- auto generated routes end -->

import BlankLayout from './layouts/BlankLayout';
import HeaderAsideFooterLayout from './layouts/HeaderAsideFooterLayout'
import HeaderFooterLayout from './layouts/HeaderFooterLayout'
import HeaderAsideFooterResponsiveLayout from './layouts/HeaderAsideFooterResponsiveLayout'
import Login from './pages/Login'
import Home from './pages/Home'
import NotFound from './pages/NotFound'
import PageError from './pages/Error';
import PageEmpty from './pages/Empty';
import PageNotPermission from './pages/NotPermission';
import {
  Curd,
  DbConfig,
  NavConfig,
  TableConfig,
  TableFieldConfig
} from './pages/private'
// 自定义路由，如果 path 相同则会覆盖自动生成部分的路由配置
const customRoutes = [
  {
    path: '/private/config/navconfig',
    childRoutes: [],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: { component: NavConfig },
  },
  {
    path: '/private/config/dbconfig',
    childRoutes: [],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: { component: DbConfig },
  },
  {
    path: '/private/config/tableconfig',
    childRoutes: [],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: { component: TableConfig },
  },
  {
    path: '/private/config/tablefieldconfig',
    childRoutes: [],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: { component: TableFieldConfig },
  },
  {
    path: '/curd/:tableId',
    childRoutes: [],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: { component: Curd },
  },
  {
    path: '/login',
    childRoutes: [],
    component: BlankLayout,
    indexRoute: { component: Login },
  },
  {
    path: '/403',
    childRoutes: [],
    component: BlankLayout,
    indexRoute: { component: PageNotPermission },
  },
  {
    path: '/null',
    childRoutes: [],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: { component: PageEmpty },
  },
  {
    path: '/500',
    childRoutes: [],
    component: BlankLayout,
    indexRoute: { component: PageError },
  },
  {
    path: '/',
    childRoutes: [{ path: '*', childRoutes: [], component: NotFound }],
    component: HeaderAsideFooterResponsiveLayout,
    // indexRoute: { component: PageEmpty },
    indexRoute: { component: Home },
  },
]

// 跳转前做一些判断,比如是否登录
function createElement(Component, props) {
  // if (props.location.pathname.indexOf('login') === -1 && localStorage.getItem('isLogin')) {
  //   localStorage.setItem('isLogin', 1)
  //   window.location.href = '#/login'
  // }
  return <Component {...props} />
}

export default (
  <Router
    createElement={createElement}
    history={hashHistory}
    routes={[...autoGeneratedRoutes, ...customRoutes]}
  />
)
