import React, { Component } from 'react';
import XtTable from '../../components/XtTable';
import { get, getById, del, update, add, getColumns } from '../../api'

const COLUMNS_CONFIG = [
  {
    id: 132,
    table_id: 30,
    table_name: "c_tablefieldconfig",
    name: "id",
    fieldname: "id",
    title: "id",
    data_type: 0,
    col_show: 1,
    col_width: 100,
    col_lock: "false",
    col_unit: null,
    col_sort: 0,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 0,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "",
    create_time: "2018-03-14T08:10:10.000Z"
  },
  {
    id: 133,
    table_id: 30,
    table_name: "c_tablefieldconfig",
    name: "table_id",
    fieldname: "table_id",
    title: "所属表字段",
    data_type: 0,
    col_show: 1,
    col_width: 100,
    col_lock: "false",
    col_unit: null,
    col_sort: 1,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 1,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "所属表字段",
    create_time: "2018-03-14T08:10:10.000Z"
  },
  {
    id: 134,
    table_id: 30,
    table_name: "c_tablefieldconfig",
    name: "table_name",
    fieldname: "table_name",
    title: "表名",
    data_type: 0,
    col_show: 1,
    col_width: 100,
    col_lock: "false",
    col_unit: null,
    col_sort: 2,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 2,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "表名",
    create_time: "2018-03-14T08:10:10.000Z"
  },
  {
    id: 135,
    table_id: 30,
    table_name: "c_tablefieldconfig",
    name: "name",
    fieldname: "name",
    title: "字段名",
    data_type: 0,
    col_show: 1,
    col_width: 100,
    col_lock: "false",
    col_unit: null,
    col_sort: 3,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 3,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "字段名",
    create_time: "2018-03-14T08:10:10.000Z"
  },
  {
    id: 131,
    table_id: 30,
    table_name: "c_tablefieldconfig",
    name: "fieldname",
    fieldname: "fieldname",
    title: "物理字段名",
    data_type: 0,
    col_show: 1,
    col_width: 100,
    col_lock: "false",
    col_unit: null,
    col_sort: 4,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 4,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "物理字段名，正常和name一致，如果取别名，则name会不一样点",
    create_time: "2018-03-14T08:10:10.000Z"
  },
  {
    id: 136,
    table_id: 30,
    table_name: "c_tablefieldconfig",
    name: "title",
    fieldname: "title",
    title: "字段名称",
    data_type: 0,
    col_show: 1,
    col_width: 100,
    col_lock: "false",
    col_unit: null,
    col_sort: 5,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 5,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "字段名称",
    create_time: "2018-03-14T08:10:10.000Z"
  },
  {
    id: 137,
    table_id: 30,
    table_name: "c_tablefieldconfig",
    name: "data_type",
    fieldname: "data_type",
    title: "数据类型",
    data_type: 0,
    col_show: 1,
    col_width: 100,
    col_lock: "false",
    col_unit: null,
    col_sort: 6,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 6,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "数据类型",
    create_time: "2018-03-14T08:10:10.000Z"
  },
  {
    id: 138,
    table_id: 30,
    table_name: "c_tablefieldconfig",
    name: "col_show",
    fieldname: "col_show",
    title: "字段-显示",
    data_type: 0,
    col_show: 1,
    col_width: 100,
    col_lock: "false",
    col_unit: null,
    col_sort: 7,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 7,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "字段-显示",
    create_time: "2018-03-14T08:10:10.000Z"
  },
  {
    id: 139,
    table_id: 30,
    table_name: "c_tablefieldconfig",
    name: "col_width",
    fieldname: "col_width",
    title: "字段-宽度",
    data_type: 0,
    col_show: 1,
    col_width: 100,
    col_lock: "false",
    col_unit: null,
    col_sort: 8,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 8,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "字段-宽度",
    create_time: "2018-03-14T08:10:10.000Z"
  },
  {
    id: 140,
    table_id: 30,
    table_name: "c_tablefieldconfig",
    name: "col_lock",
    fieldname: "col_lock",
    title: "字段-锁定",
    data_type: 0,
    col_show: 1,
    col_width: 100,
    col_lock: "false",
    col_unit: null,
    col_sort: 9,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 9,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "字段-锁定",
    create_time: "2018-03-14T08:10:10.000Z"
  },
  {
    id: 141,
    table_id: 30,
    table_name: "c_tablefieldconfig",
    name: "col_unit",
    fieldname: "col_unit",
    title: "字段-单位",
    data_type: 0,
    col_show: 1,
    col_width: 100,
    col_lock: "false",
    col_unit: null,
    col_sort: 10,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 10,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "字段-单位",
    create_time: "2018-03-14T08:10:10.000Z"
  },
  {
    id: 143,
    table_id: 30,
    table_name: "c_tablefieldconfig",
    name: "col_sort",
    fieldname: "col_sort",
    title: "字段-顺序",
    data_type: 0,
    col_show: 1,
    col_width: 100,
    col_lock: "false",
    col_unit: null,
    col_sort: 11,
    col_sortable: true,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 11,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "字段-顺序",
    create_time: "2018-03-14T08:10:10.000Z"
  },
  {
    id: 142,
    table_id: 30,
    table_name: "c_tablefieldconfig",
    name: "col_sortable",
    fieldname: "col_sortable",
    title: "字段-排序",
    data_type: 0,
    col_show: 1,
    col_width: 100,
    col_lock: "false",
    col_unit: null,
    col_sort: 12,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 12,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "字段-排序",
    create_time: "2018-03-14T08:10:10.000Z"
  },
  {
    id: 144,
    table_id: 30,
    table_name: "c_tablefieldconfig",
    name: "col_align",
    fieldname: "col_align",
    title: "字段-对齐",
    data_type: 0,
    col_show: 1,
    col_width: 100,
    col_lock: "false",
    col_unit: null,
    col_sort: 13,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 13,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "字段-对齐",
    create_time: "2018-03-14T08:10:10.000Z"
  },
  {
    id: 146,
    table_id: 30,
    table_name: "c_tablefieldconfig",
    name: "form_show",
    fieldname: "form_show",
    title: "表单-是否展示",
    data_type: 0,
    col_show: 1,
    col_width: 100,
    col_lock: "false",
    col_unit: null,
    col_sort: 14,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 14,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "表单-是否展示",
    create_time: "2018-03-14T08:10:10.000Z"
  },
  {
    id: 145,
    table_id: 30,
    table_name: "c_tablefieldconfig",
    name: "form_type",
    fieldname: "form_type",
    title: "表单-类型",
    data_type: 0,
    col_show: 1,
    col_width: 100,
    col_lock: "false",
    col_unit: null,
    col_sort: 15,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 15,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "表单-类型",
    create_time: "2018-03-14T08:10:10.000Z"
  },
  {
    id: 147,
    table_id: 30,
    table_name: "c_tablefieldconfig",
    name: "form_disabled",
    fieldname: "form_disabled",
    title: "表单-禁用",
    data_type: 0,
    col_show: 1,
    col_width: 100,
    col_lock: "false",
    col_unit: null,
    col_sort: 16,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 16,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "表单-禁用",
    create_time: "2018-03-14T08:10:10.000Z"
  },
  {
    id: 148,
    table_id: 30,
    table_name: "c_tablefieldconfig",
    name: "form_sort",
    fieldname: "form_sort",
    title: "表单-顺序",
    data_type: 0,
    col_show: 1,
    col_width: 100,
    col_lock: "false",
    col_unit: null,
    col_sort: 17,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 17,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "表单-顺序",
    create_time: "2018-03-14T08:10:10.000Z"
  },
  {
    id: 149,
    table_id: 30,
    table_name: "c_tablefieldconfig",
    name: "form_format",
    fieldname: "form_format",
    title: "表单-格式",
    data_type: 0,
    col_show: 1,
    col_width: 100,
    col_lock: "false",
    col_unit: null,
    col_sort: 18,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 18,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "表单-格式",
    create_time: "2018-03-14T08:10:10.000Z"
  },
  {
    id: 150,
    table_id: 30,
    table_name: "c_tablefieldconfig",
    name: "form_required",
    fieldname: "form_required",
    title: "表单-必填",
    data_type: 0,
    col_show: 1,
    col_width: 100,
    col_lock: "false",
    col_unit: null,
    col_sort: 19,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 19,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "表单-必填",
    create_time: "2018-03-14T08:10:10.000Z"
  },
  {
    id: 151,
    table_id: 30,
    table_name: "c_tablefieldconfig",
    name: "form_validate_msg",
    fieldname: "form_validate_msg",
    title: "表单-验证提示信息",
    data_type: 0,
    col_show: 1,
    col_width: 100,
    col_lock: "false",
    col_unit: null,
    col_sort: 20,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 20,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "表单-验证提示信息",
    create_time: "2018-03-14T08:10:10.000Z"
  },
  {
    id: 152,
    table_id: 30,
    table_name: "c_tablefieldconfig",
    name: "form_rules",
    fieldname: "form_rules",
    title: "表单-验证",
    data_type: 0,
    col_show: 1,
    col_width: 100,
    col_lock: "false",
    col_unit: null,
    col_sort: 21,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 21,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "表单-验证",
    create_time: "2018-03-14T08:10:10.000Z"
  },
  {
    id: 153,
    table_id: 30,
    table_name: "c_tablefieldconfig",
    name: "remark",
    fieldname: "remark",
    title: "备注",
    data_type: 0,
    col_show: 1,
    col_width: 100,
    col_lock: "false",
    col_unit: null,
    col_sort: 22,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 22,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "备注",
    create_time: "2018-03-14T08:10:10.000Z"
  },
  {
    id: 154,
    table_id: 30,
    table_name: "c_tablefieldconfig",
    name: "create_time",
    fieldname: "create_time",
    title: "创建时间",
    data_type: 0,
    col_show: 1,
    col_width: 100,
    col_lock: "false",
    col_unit: null,
    col_sort: 23,
    col_sortable: null,
    col_align: "center",
    form_show: 1,
    form_type: 1,
    form_disabled: 0,
    form_sort: 23,
    form_format: null,
    form_required: 0,
    form_validate_msg: null,
    form_rules: null,
    remark: "创建时间",
    create_time: "2018-03-14T08:10:10.000Z"
  }
]

const FILTER = [
  { text: "表ID", value: "table_id" },
  { text: "id", value: "id" },
  { text: "表名", value: "table_name" },
]

export default class TableFieldConfigTable extends Component {
  static displayName = 'TableFieldConfigTable';
  render() {
    const TABLE_NAME = 'c_tablefieldconfig'
    const api = { get, getById, del, update, add, getColumns }
    // 这里的key不能少，否则react会缓存，不重新渲染
    return (
      <div className="table-page" key={TABLE_NAME}>
        <XtTable {...api} name={TABLE_NAME} columns={COLUMNS_CONFIG} filter={FILTER} />
      </div>
    );
  }
}
